---
platform: linux

inputs:
- name: k8s_deployment
- name: bosh_state
- name: terraform_state

params:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  AWS_REGION:
  KUBO_RELEASE:

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x k8s_deployment/ci/tasks/deploy_k8s/deploy_k8s.sh
    k8s_deployment/ci/tasks/deploy_k8s/deploy_k8s.sh
