---
platform: linux

inputs:
- name: k8s_deployment
- name: terraform_state

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x k8s_deployment/ci/tasks/configure_jumpbox/configure_jumpbox.sh
    k8s_deployment/ci/tasks/configure_jumpbox/configure_jumpbox.sh